# Exported from Render on 2024-04-20T17:23:49Z
services:
- type: web
  name: morbitz
  runtime: node
  repo: https://https://github.com/bacontheoverseer/morbitz
  plan: free
  region: oregon
  buildCommand: npm i
  startCommand: node index.js
version: "1"
